dataset: {path: /home/michal/Documents/timit/timit}
test: {model: /home/michal/Documents/models/weights_ctc-29-01-2022/epoch9_lr0.001_cvtensor(74.5483).pkl}
trained-models: {path: /home/michal/Documents/test/dir2}
training: {max-epochs: 13}
word-spotting:
  dictionary: [cat]
